import express from "express";

const users = [
  {
    id: 1,
    name: "Haris",
    job: "Designer",
    age: "23",
    city: "Rawalpindi",
  },
  {
    id: 2,
    name: "Ali",
    job: "Developer",
    age: "28",
    city: "Islamabad",
  },
  {
    id: 3,
    name: "Ahmed",
    job: "Engineer",
    age: "31",
    city: "Lahore",
  },
  {
    id: 4,
    name: "Usman",
    job: "Manager",
    age: "35",
    city: "Karachi",
  },
  {
    id: 5,
    name: "Hamza",
    job: "Teacher",
    age: "26",
    city: "Peshawar",
  },
  {
    id: 6,
    name: "Bilal",
    job: "Writer",
    age: "29",
    city: "Multan",
  },
  {
    id: 7,
    name: "Ahsan",
    job: "Designer",
    age: "24",
    city: "Faisalabad",
  },
  {
    id: 8,
    name: "Omar",
    job: "Developer",
    age: "32",
    city: "Rawalpindi",
  },
  {
    id: 9,
    name: "Zain",
    job: "Engineer",
    age: "27",
    city: "Islamabad",
  },
  {
    id: 10,
    name: "Saad",
    job: "Manager",
    age: "38",
    city: "Lahore",
  },
  {
    id: 11,
    name: "Danish",
    job: "Teacher",
    age: "25",
    city: "Karachi",
  },
  {
    id: 12,
    name: "Fahad",
    job: "Designer",
    age: "30",
    city: "Peshawar",
  },
  {
    id: 13,
    name: "Talha",
    job: "Developer",
    age: "22",
    city: "Multan",
  },
  {
    id: 14,
    name: "Waleed",
    job: "Writer",
    age: "34",
    city: "Faisalabad",
  },
  {
    id: 15,
    name: "Hassan",
    job: "Engineer",
    age: "28",
    city: "Rawalpindi",
  },
  {
    id: 16,
    name: "Huzaifa",
    job: "Manager",
    age: "33",
    city: "Islamabad",
  },
  {
    id: 17,
    name: "Abdullah",
    job: "Teacher",
    age: "21",
    city: "Lahore",
  },
  {
    id: 18,
    name: "Muneeb",
    job: "Designer",
    age: "26",
    city: "Karachi",
  },
  {
    id: 19,
    name: "Shahzaib",
    job: "Developer",
    age: "29",
    city: "Peshawar",
  },
  {
    id: 20,
    name: "Rayan",
    job: "Engineer",
    age: "36",
    city: "Multan",
  },
  {
    id: 21,
    name: "Arham",
    job: "Writer",
    age: "23",
    city: "Faisalabad",
  },
  {
    id: 22,
    name: "Sameer",
    job: "Manager",
    age: "40",
    city: "Rawalpindi",
  },
  {
    id: 23,
    name: "Yousuf",
    job: "Teacher",
    age: "27",
    city: "Islamabad",
  },
  {
    id: 24,
    name: "Ibrahim",
    job: "Designer",
    age: "31",
    city: "Lahore",
  },
  {
    id: 25,
    name: "Rayyan",
    job: "Developer",
    age: "24",
    city: "Karachi",
  },
  {
    id: 26,
    name: "Adeel",
    job: "Engineer",
    age: "30",
    city: "Peshawar",
  },
  {
    id: 27,
    name: "Noman",
    job: "Writer",
    age: "35",
    city: "Multan",
  },
  {
    id: 28,
    name: "Asad",
    job: "Manager",
    age: "28",
    city: "Faisalabad",
  },
  {
    id: 29,
    name: "Imran",
    job: "Teacher",
    age: "42",
    city: "Rawalpindi",
  },
  {
    id: 30,
    name: "Kashif",
    job: "Designer",
    age: "25",
    city: "Islamabad",
  },
  {
    id: 31,
    name: "Sufyan",
    job: "Developer",
    age: "27",
    city: "Lahore",
  },
  {
    id: 32,
    name: "Adnan",
    job: "Engineer",
    age: "33",
    city: "Karachi",
  },
  {
    id: 33,
    name: "Rizwan",
    job: "Manager",
    age: "39",
    city: "Peshawar",
  },
  {
    id: 34,
    name: "Shayan",
    job: "Writer",
    age: "22",
    city: "Multan",
  },
  {
    id: 35,
    name: "Faisal",
    job: "Teacher",
    age: "37",
    city: "Faisalabad",
  },
  {
    id: 36,
    name: "Taha",
    job: "Designer",
    age: "29",
    city: "Rawalpindi",
  },
  {
    id: 37,
    name: "Junaid",
    job: "Developer",
    age: "34",
    city: "Islamabad",
  },
  {
    id: 38,
    name: "Rehan",
    job: "Engineer",
    age: "26",
    city: "Lahore",
  },
  {
    id: 39,
    name: "Salman",
    job: "Manager",
    age: "41",
    city: "Karachi",
  },
  {
    id: 40,
    name: "Musa",
    job: "Teacher",
    age: "23",
    city: "Peshawar",
  },
  {
    id: 41,
    name: "Abbas",
    job: "Designer",
    age: "32",
    city: "Multan",
  },
  {
    id: 42,
    name: "Zubair",
    job: "Developer",
    age: "28",
    city: "Faisalabad",
  },
  {
    id: 43,
    name: "Kamil",
    job: "Writer",
    age: "25",
    city: "Rawalpindi",
  },
  {
    id: 44,
    name: "Shahbaz",
    job: "Engineer",
    age: "36",
    city: "Islamabad",
  },
  {
    id: 45,
    name: "Naveed",
    job: "Manager",
    age: "43",
    city: "Lahore",
  },
  {
    id: 46,
    name: "Irfan",
    job: "Teacher",
    age: "30",
    city: "Karachi",
  },
  {
    id: 47,
    name: "Kamran",
    job: "Designer",
    age: "27",
    city: "Peshawar",
  },
  {
    id: 48,
    name: "Rafay",
    job: "Developer",
    age: "24",
    city: "Multan",
  },
  {
    id: 49,
    name: "Dawood",
    job: "Engineer",
    age: "29",
    city: "Faisalabad",
  },
  {
    id: 50,
    name: "Sami",
    job: "Writer",
    age: "33",
    city: "Rawalpindi",
  },
  {
    id: 51,
    name: "Farhan",
    job: "Manager",
    age: "38",
    city: "Islamabad",
  },
  {
    id: 52,
    name: "Yahya",
    job: "Teacher",
    age: "26",
    city: "Lahore",
  },
  {
    id: 53,
    name: "Ammar",
    job: "Designer",
    age: "23",
    city: "Karachi",
  },
  {
    id: 54,
    name: "Murtaza",
    job: "Developer",
    age: "31",
    city: "Peshawar",
  },
  {
    id: 55,
    name: "Shahmeer",
    job: "Engineer",
    age: "35",
    city: "Multan",
  },
  {
    id: 56,
    name: "Ayan",
    job: "Writer",
    age: "21",
    city: "Faisalabad",
  },
  {
    id: 57,
    name: "Moiz",
    job: "Manager",
    age: "30",
    city: "Rawalpindi",
  },
  {
    id: 58,
    name: "Rameez",
    job: "Teacher",
    age: "34",
    city: "Islamabad",
  },
  {
    id: 59,
    name: "Shoaib",
    job: "Designer",
    age: "28",
    city: "Lahore",
  },
  {
    id: 60,
    name: "Arslan",
    job: "Developer",
    age: "37",
    city: "Karachi",
  },
  {
    id: 61,
    name: "Hammad",
    job: "Engineer",
    age: "25",
    city: "Peshawar",
  },
  {
    id: 62,
    name: "Qasim",
    job: "Writer",
    age: "40",
    city: "Multan",
  },
  {
    id: 63,
    name: "Nashit",
    job: "Manager",
    age: "29",
    city: "Faisalabad",
  },
  {
    id: 64,
    name: "Azan",
    job: "Teacher",
    age: "22",
    city: "Rawalpindi",
  },
  {
    id: 65,
    name: "Rafay",
    job: "Designer",
    age: "26",
    city: "Islamabad",
  },
  {
    id: 66,
    name: "Zeeshan",
    job: "Developer",
    age: "33",
    city: "Lahore",
  },
  {
    id: 67,
    name: "Waqar",
    job: "Engineer",
    age: "39",
    city: "Karachi",
  },
  {
    id: 68,
    name: "Asim",
    job: "Writer",
    age: "27",
    city: "Peshawar",
  },
  {
    id: 69,
    name: "Nouman",
    job: "Manager",
    age: "36",
    city: "Multan",
  },
  {
    id: 70,
    name: "Saqib",
    job: "Teacher",
    age: "31",
    city: "Faisalabad",
  },
  {
    id: 71,
    name: "Mahir",
    job: "Designer",
    age: "24",
    city: "Rawalpindi",
  },
  {
    id: 72,
    name: "Aariz",
    job: "Developer",
    age: "29",
    city: "Islamabad",
  },
  {
    id: 73,
    name: "Sheryar",
    job: "Engineer",
    age: "32",
    city: "Lahore",
  },
  {
    id: 74,
    name: "Hashir",
    job: "Manager",
    age: "27",
    city: "Karachi",
  },
  {
    id: 75,
    name: "Mikael",
    job: "Teacher",
    age: "35",
    city: "Peshawar",
  },
  {
    id: 76,
    name: "Ehsan",
    job: "Writer",
    age: "23",
    city: "Multan",
  },
  {
    id: 77,
    name: "Awais",
    job: "Designer",
    age: "30",
    city: "Faisalabad",
  },
  {
    id: 78,
    name: "Rashid",
    job: "Developer",
    age: "41",
    city: "Rawalpindi",
  },
  {
    id: 79,
    name: "Nabeel",
    job: "Engineer",
    age: "28",
    city: "Islamabad",
  },
  {
    id: 80,
    name: "Shahid",
    job: "Manager",
    age: "44",
    city: "Lahore",
  },
  {
    id: 81,
    name: "Waqas",
    job: "Teacher",
    age: "26",
    city: "Karachi",
  },
  {
    id: 82,
    name: "Sarmad",
    job: "Designer",
    age: "34",
    city: "Peshawar",
  },
  {
    id: 83,
    name: "Haseeb",
    job: "Developer",
    age: "25",
    city: "Multan",
  },
  {
    id: 84,
    name: "Zarar",
    job: "Engineer",
    age: "37",
    city: "Faisalabad",
  },
  {
    id: 85,
    name: "Mansoor",
    job: "Writer",
    age: "42",
    city: "Rawalpindi",
  },
  {
    id: 86,
    name: "Aqib",
    job: "Manager",
    age: "31",
    city: "Islamabad",
  },
  {
    id: 87,
    name: "Furqan",
    job: "Teacher",
    age: "29",
    city: "Lahore",
  },
  {
    id: 88,
    name: "Salar",
    job: "Designer",
    age: "22",
    city: "Karachi",
  },
  {
    id: 89,
    name: "Hamdan",
    job: "Developer",
    age: "36",
    city: "Peshawar",
  },
  {
    id: 90,
    name: "Zaid",
    job: "Engineer",
    age: "24",
    city: "Multan",
  },
  {
    id: 91,
    name: "Rohan",
    job: "Writer",
    age: "28",
    city: "Faisalabad",
  },
  {
    id: 92,
    name: "Daniyal",
    job: "Manager",
    age: "33",
    city: "Rawalpindi",
  },
  {
    id: 93,
    name: "Huzefa",
    job: "Teacher",
    age: "39",
    city: "Islamabad",
  },
  {
    id: 94,
    name: "Areeb",
    job: "Designer",
    age: "27",
    city: "Lahore",
  },
  {
    id: 95,
    name: "Shahzaib",
    job: "Developer",
    age: "30",
    city: "Karachi",
  },
  {
    id: 96,
    name: "Momin",
    job: "Engineer",
    age: "26",
    city: "Peshawar",
  },
  {
    id: 97,
    name: "Raza",
    job: "Writer",
    age: "35",
    city: "Multan",
  },
  {
    id: 98,
    name: "Haris",
    job: "Manager",
    age: "23",
    city: "Faisalabad",
  },
  {
    id: 99,
    name: "Aftab",
    job: "Teacher",
    age: "40",
    city: "Rawalpindi",
  },
  {
    id: 100,
    name: "Kashan",
    job: "Designer",
    age: "32",
    city: "Islamabad",
  },
];

const server = express();

server.use(express.json());

server.get("/", (req, res) => {
  res.send("Welcome");
});

server.get("/users", (req, res) => {
  let result = users;
  for (let [key, value] of Object.entries(req.query)) {
    if (key === "minAge") {
      result = result.filter((user) => Number(user.age >= Number(value)));
    } else {
        result = result.filter(
              (user) =>
                user[key].toLocaleLowerCase() === value.toLocaleLowerCase(),
            );
    }
    console.log(`${key} , ${value}`);
  }
  console.log();
  res.send(result);
});

server.get("/users/:id", (req, res) => {
  console.log(req.params.id);
  res.json(users.filter((user) => Number(user.id) === Number(req.params.id)));
});

server.post("/users", (req, res) => {});

server.put("/users", (req, res) => {
  res.send("Put Users");
});

server.delete("/users", (req, res) => {
  res.send("Delete Users");
});

server.listen(3000, () => {
  console.log("Express started");
});
